"""TODO: will keep all key words for transformations"""
states_abbreviated = [
        'AL',
        'AK',
        'AZ',
        'AR',
        'CA',
        'CO',
        'CT',
        'DC',
        'DE',
        'FL',
        'GA',
        'HI',
        'ID',
        'IL',
        'IN',
        'IA',
        'KS',
        'KY',
        'LA',
        'ME',
        'MD',
        'MA',
        'MI',
        'MN',
        'MS',
        'MO',
        'MT',
        'NE',
        'NV',
        'NH',
        'NJ',
        'NM',
        'NY',
        'NC',
        'ND',
        'OH',
        'OK',
        'OR',
        'PA',
        'RI',
        'SC',
        'SD',
        'TN',
        'TX',
        'UT',
        'VT',
        'VA',
        'WA',
        'WV',
        'WI',
        'WY',
    ]

street_ending = {
        "AVE": "AVENUE",
        "BLVD": "BOULEVARD",
        "CIR": "CIRCLE",
        "CT": "COURT",
        "DR": "DRIVE",
        "HWY": "HIGHWAY",
        "LN": "LANE",
        "PL": "PLACE",
        "ST": "STREET",
        "RD": "ROAD",
        "TERR": "TERRACE",
        "TER": "TERRACE",
        "TRL": "TRAIL",
        "WY": "WAY",
    }
