name: List Pull Requests and Output as CSV

on:
  push:
    branches:
      - n2020h-issues-to-csv
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  # pull_request:
  #   types: [opened, closed, reopened]
  #   branches: 
  #     - n2020h-issues-to-csv

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to access any scripts or tools you might need
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js to use jq command
    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '20'

    # Generate pull requests CSV
    - name: Generate pull requests CSV
      run: |
        run: |
        echo "PR Number,Title,Description,Author,State,Number of Commits,Number of Files Changed,Labels,Assignees,Reviewers" > hackforla_PRs.csv
        jq -r '.[] | [
          .number,
          .title,
          .body,
          .user.login,
          .state,
          .commits,
          .changed_files,
          (.labels | map(.name) | join(",")),
          (.assignees | map(.login) | join(",")),
          (.requested_reviewers | map(.login) | join(","))
        ] | @csv' pulls.json >> hackforla_PRs.csv

    # Commit and push the generated CSV to the repository
    - name: Commit and push CSV
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -f hackforla_PRs.csv
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push --force origin HEAD:refs/heads/n2020h-issues-to-csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
